#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 1.0
PACKAGE_NAME = Zcode
APP_NAME = Zcode
Zcode_APPLICATION_ICON = apple-green.png


#
# Resource files
#
Zcode_RESOURCE_FILES = \
Resources/Zcode.gorm \
Resources/Main.gsmarkup \
Resources/MainMenu-GNUstep.gsmarkup \
Resources/MainMenu-OSX.gsmarkup \
Resources/ProjectDocument.gorm \
Resources/apple-green.png 


#
# Header files
#
Zcode_HEADER_FILES = \
AppController.h \
ProjectDocument.h \
GAFContainer.h \
PBXProject.h \
NSDictionary+SmartUnpack.h \
PBXGroup.h \
PBXFileReference.h \
PBXVariantGroup.h

#
# Class files
#
Zcode_OBJC_FILES = \
AppController.m \
ProjectDocument.m \
GAFContainer.m \
PBXProject.m \
NSDictionary+SmartUnpack.m \
PBXGroup.m \
PBXFileReference.m \
PBXVariantGroup.m

#
# Other sources
#
Zcode_OBJC_FILES += \
Zcode_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
