/*
   Project: Zcode

   Copyright (C) 2011 Free Software Foundation

   Author: Ivan Vucica,,,

   Created: 2011-01-01 19:53:11 +0100 by ivucica

   This application is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.

   This application is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU General Public
   License along with this library; if not, write to the Free
   Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA.
*/

#import "NSDictionary+SmartUnpack.h"
#import "ProjectDocument.h"

@implementation NSDictionary(smartUnpack)


-(id)unpackObjectWithKey:(NSString*)key forDocument:(ProjectDocument*)doc pbxDictionary:(NSDictionary*)objects required:(BOOL)required error:(NSError**)error
{
  id o = [self objectForKey:key];
  if([o isKindOfClass:[NSString class]])
  {
    id pbxo = [objects objectForKey:o];
    if(pbxo && [pbxo isKindOfClass:[NSDictionary class]]) // check if object exists and is a dictionary
    {
      id decoded = [doc newObjectSpecifiedByISAWithPBXDictionary:objects withKey:o required:required error:error];
      if(decoded)
      {
        return [decoded autorelease];
      }
      else
      {
      
        if(error && !*error)
        {
          *error = [NSError errorWithDomain:NSOSStatusErrorDomain
                                       code:0 // FIXME use correct key
                                   userInfo:[NSDictionary dictionaryWithObjectsAndKeys:[NSString stringWithFormat:@"NSDictionary smart unpack could not unpack %@ using %@", key, o], NSLocalizedDescriptionKey,
                                                                                       [doc fileName], NSFilePathErrorKey,
                                                                                       @"Check that project's project.pbxproj is generated by a supported version of Zcode and Xcode.", NSLocalizedRecoverySuggestionErrorKey,
                                                                                       nil]];

        }
        return nil;      
      }
    }
  }
  if(!o)
  {
    if(error)
    {
      *error = [NSError errorWithDomain:NSOSStatusErrorDomain
                                   code:0 // FIXME use correct key
                               userInfo:[NSDictionary dictionaryWithObjectsAndKeys:[NSString stringWithFormat:@"NSDictionary smart unpack could not find %@", key], NSLocalizedDescriptionKey,
                                                                                   [doc fileName], NSFilePathErrorKey,
                                                                                   @"Check that project's project.pbxproj is generated by a supported version of Zcode and Xcode.", NSLocalizedRecoverySuggestionErrorKey,
                                                                                   nil]];

      for(NSString *keyit in [objects allKeys])
      {
        id obj = [objects objectForKey:keyit];
        NSLog(@"^^                  %@ <=> %@, %@, %@", key, keyit, [obj objectForKey:@"isa"], [obj objectForKey:@"name"]);
        
      }
    }
  }
  return o;
}

@end