/*
   Project: Zcode

   Copyright (C) 2010 Ivan Vucica

   Author: Ivan Vucica,,,

   Created: 2010-12-05 22:36:24 +0100 by ivucica

   This application is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   This application is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with this application; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/

#import "ProjectDocument.h"
#import "GAFContainer.h"
#import "PBXProject.h"
#import "ProjectDetailListDataSource.h"
#import "ZCEditorViewController.h"
#import "PBXProjLib/PBXProjectReader.h"

#if !GNUSTEP
#import <objc/runtime.h>
#endif

@implementation ProjectDocument

@synthesize groupsAndFilesView;

#pragma mark -
#pragma mark Init and deinit

- (id)init
{
  if((self=[super init]))
  {
    pbxProject = [[PBXProject alloc] init];
    gafContainers = [[NSArray alloc] initWithObjects:[pbxProject mainGroup],
                                                     nil];
    editorViewController = [[ZCEditorViewController alloc] initWithNibName:@"ZCEditorViewController" bundle:nil];
  }
  return self;
}

-(id)initWithContentsOfFile:(NSString*)file ofType:(NSString*)type
{
  // overriding this function solely so it doesn't call [self init]; we want
  // it to call [super init] so in case of creation of new document, we can
  // just initialize stuff in init without worrying loaded documents will have
  // to free stuff while loading in readFromURL:ofType:error:.
  //
  // that's the sole reason.
  
  if((self=[super init]))
  {
    NSError *error = nil;

    if([self readFromURL:[NSURL fileURLWithPath:file] ofType:type error:&error])
    {
      [self setFileName:file];
      editorViewController = [[ZCEditorViewController alloc] initWithNibName:@"ZCEditorViewController" bundle:nil];
    }
    else
    {
      if(!error)
        error = [NSError errorWithDomain:NSOSStatusErrorDomain 
                                    code:0 // FIXME use correct key
                                userInfo:[NSDictionary dictionaryWithObjectsAndKeys:@"Unknown error loading pbxproj", NSLocalizedDescriptionKey,
                                                                                    file, NSFilePathErrorKey,
                                                                                    @"Check that project's project.pbxproj exists, that it is not corrupted, and that it is generated by a supported version of Zcode and Xcode.", NSLocalizedRecoverySuggestionErrorKey,
                                                                                    nil]];
      [self presentError:error];
      
      [self release];
      return nil;
    }
    
  }
  return self;
}

- (void)windowControllerDidLoadNib:(NSWindowController *) aController
{
  toolbar = [[NSToolbar alloc] initWithIdentifier:@"toolbar"]; // FIXME toolbar must be inited only once.
  NSWindow* w = [self windowForSheet]; // FIXME is the right way to get NSWindow for this NSDocument?
  //[toolbar insertItemWithItemIdentifier:@"tb_build" atIndex:[[toolbar items] count]];
  [toolbar setDelegate:self];
  [w setToolbar:toolbar];
  //[window toggleToolbarShown:self];
  [toolbar setVisible:YES];

  NSRect editorRect = NSZeroRect;
  if(editorViewContainer)
  {
    editorRect.size = editorViewContainer.frame.size;
    if(editorViewController)
    {
      if(editorViewController.view)
      {
        editorViewController.view.frame = editorRect;

        [editorViewContainer addSubview:editorViewController.view];
      }
      else
      {
        NSLog(@"Editor view does not exist!");
      }
    }
    else
    {
      NSLog(@"Editor view controller failed to load!");
    }
  }
  else
  {
    NSLog(@"Editor view container does not exist!");
  }
}

// an NSDocument must specify which nib file it uses
-(NSString*)windowNibName
{
  return @"ProjectDocument";
}

-(void)dealloc
{
  NSLog(@"PD dealloc");
  [toolbar release];
#if GNUSTEP
  for(id container in gafContainers)
  {
    [container release];
  }
#endif
  [editorViewController release];
  [gafContainers release];
  [pbxProject release];
  [super dealloc];
}

#pragma mark -
#pragma mark Loading and saving

-(void)_handleIOError:(NSError**)error errorString:(NSString*)errStr
{

    if(error)
    {
      *error = [NSError errorWithDomain:NSOSStatusErrorDomain
                                   code:0 // FIXME use correct key
                               userInfo:[NSDictionary dictionaryWithObjectsAndKeys:errStr, NSLocalizedDescriptionKey,
                                                                                   [self fileName], NSFilePathErrorKey,
                                                                                   @"Check that project's project.pbxproj is generated by a supported version of Zcode and Xcode.", NSLocalizedRecoverySuggestionErrorKey,
                                                                                   nil]];
    }
}

-(BOOL)readFromURL:(NSURL*)url ofType:(NSString*)type error:(NSError**)error
{
  NSString *path = [url path];
  NSString *pbxProjPath = [path stringByAppendingPathComponent:@"project.pbxproj"];

  [self setFileName:pbxProjPath];


  if(pbxProject)
    [pbxProject release];

  PBXProjectReader *reader = [[[PBXProjectReader alloc] initWithFile:pbxProjPath] autorelease];
  pbxProject = [reader.rootObject retain];
  if(reader.errorOccurred)
  {
    [self _handleIOError:error errorString:reader.errorMessage];
    return NO;
  }

  pbxProject.owner = self;

  [gafContainers release];
  gafContainers = [[NSArray alloc] initWithObjects:[pbxProject.mainGroup retain], nil];

  return YES;
}

#pragma mark -
#pragma mark Project-related commands
-(IBAction)build:(id)sender
{
  NSLog(@"build");
}

#pragma mark -
#pragma mark Toolbar delegate
- (NSToolbarItem*)toolbar: (NSToolbar*)toolbar
    itemForItemIdentifier: (NSString*)itemIdentifier
willBeInsertedIntoToolbar: (BOOL)flag
{
  NSToolbarItem* ti = [[[NSToolbarItem alloc] initWithItemIdentifier:itemIdentifier] autorelease];
  [ti setLabel:@"Build"];
  [ti setPaletteLabel:@"Build"];
  [ti setToolTip:@"Build"];
  [ti setTarget:self];
  [ti setAction:@selector(build:)];
  NSSize sz = {48,48};
  [ti setMinSize:sz];
  [ti setImage:[[[NSImage alloc] initWithContentsOfFile:@"/usr/share/icons/gnome/48x48/actions/system-run.png"] autorelease]];

  return ti;
}
// required method
- (NSArray*) toolbarAllowedItemIdentifiers: (NSToolbar*)toolbar
{
  return [NSArray arrayWithObjects:@"build", nil];

}
// required method
- (NSArray*) toolbarDefaultItemIdentifiers: (NSToolbar*)toolbar
{
  return [NSArray arrayWithObjects:@"build", nil];

}

#pragma mark -
#pragma mark Outline view

- (NSInteger)outlineView:(NSOutlineView *)outlineView numberOfChildrenOfItem:(id)item
{
  if(item == nil)
  {
    return [gafContainers count];
  }
  if([item respondsToSelector:@selector(numberOfChildrenForOutlineView:)])
  {
    return [item numberOfChildrenForOutlineView:outlineView];
  }
  return 0;
}
- (id)outlineView:(NSOutlineView *)outlineView objectValueForTableColumn:(NSTableColumn *)tableColumn byItem:(id)item
{
  return item;
}
- (BOOL)outlineView:(NSOutlineView *)outlineView isItemExpandable:(id)item
{
  if([item respondsToSelector:@selector(isExpandableForOutlineView:)])
  {
    return [item isExpandableForOutlineView:outlineView];
  }
  return NO;
}
- (id)outlineView:(NSOutlineView *)outlineView child:(NSInteger)index ofItem:(id)item
{
  if(item == nil)
  {
    return [gafContainers objectAtIndex:index];
  }
  if([item respondsToSelector:@selector(child:forOutlineView:)])
  {
    return [item child:index forOutlineView:outlineView];
  }
  return nil;
}

- (void)outlineView:(NSOutlineView *)outlineView setObjectValue:(id)objectValue forTableColumn:(NSTableColumn *)tableColumn byItem:(id)item
{
  if(item == nil)
    return;
  if([item respondsToSelector:@selector(outlineView:setObjectValue:forTableColumn:)])
  {
    [item outlineView:outlineView setObjectValue:objectValue forTableColumn:tableColumn];
  }
}


- (BOOL)outlineView:(NSOutlineView *)outlineView shouldEditTableColumn:(NSTableColumn*)tableColumn item:(id)item
{
  // FIXME some stuff should be queried if it wants editing right now
  // just asking if it responds to "update" function is not enough
  if(item == nil)
    return NO;
  return ([item respondsToSelector:@selector(outlineView:setObjectValue:forTableColumn:)]);
  
}

- (void)outlineView:(NSOutlineView *)outlineView willDisplayCell:(NSCell*)cell forTableColumn:(NSTableColumn*)tableColumn item:(id)item
{

  if(item == nil)
    return;
    
  if([item respondsToSelector:@selector(outlineView:willDisplayCell:forTableColumn:)])
    [item outlineView:outlineView willDisplayCell:cell forTableColumn:tableColumn];
}
  
- (void)outlineViewSelectionDidChange:(NSNotification *)notification
{
  NSMutableArray *leafs = [[NSMutableArray alloc] init];
  id item = [groupsAndFilesView itemAtRow:[groupsAndFilesView selectedRow]];
  [item addLeafsToArray:leafs];
  projectDetailListDataSource.items = leafs;
  
  if (leafs.count == 1) {
	  [self switchEditor:item];
  }
}


#pragma mark -
#pragma mark Editor management
- (void)switchEditor:(id)item
{
  if(!editorViewContainer)
  {
    NSLog(@"Cannot switch editor, editor view container does not exist!");
    return;
  }
  [editorViewController.view removeFromSuperview];
  [editorViewController release];
  NSString *editorType = [item desiredEditor];
  
  Class classFromIsa;
#if GNUSTEP
  classFromIsa = objc_lookup_class([editorType UTF8String]);
#else
  classFromIsa = objc_lookUpClass([editorType UTF8String]);
#endif

  editorViewController = [[classFromIsa alloc] initWithNibName:editorType bundle:nil];
  if(editorViewController)
  {
    [editorViewContainer addSubview:editorViewController.view];
    NSRect editorRect = NSZeroRect;
    editorRect.size = editorViewContainer.frame.size;
    editorViewController.view.frame = editorRect;
  }
  else
  {
    NSLog(@"Editor view controller %@ failed to load", editorType);
  }
}

#pragma mark -
#pragma mark PBXPathedItem

- (NSString *)path
{
  return [[self fileName] stringByDeletingLastPathComponent];
}

@end

